config/routes.rb
Rails.application.routes.draw do
  resources :articles

=begin  get 'articles/index'

  get 'articles/show'

  get 'articles/new'

  get 'articles/create'

  get 'articles/edit'

  get 'articles/update'

  get 'articles/destroy'
=end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @article.destroy
    redirect_to restaurants_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form_for.html.erb
<%= form_for(@article) do |a| %>
  <%= a.label :title %>
  <%= a.text_field :title %>
  <%= a.label :content %>
  <%= a.text_field :content %>
  <%= a.submit %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<h1> something </h1>
  <% @articles.each do |article| %>
    <h2><%= link_to article.title, article_path(article) %></h2>
<% end %>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<h1> Show </h1>
<h2><%= @article.title %></h2>
<h3><%= @article.content %></h3>
<%= link_to "Destroy", article_path(@article),
      method: :destroy,
      data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>